version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb_pdm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pdm_db
      - POSTGRES_USER=pdm_user
      - POSTGRES_PASSWORD=pdm_password
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "effective_cache_size=12GB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "max_wal_size=10GB"
      - "-c"
      - "work_mem=256MB"
      - "-c"
      - "max_parallel_workers=16"
      - "-c"
      - "max_parallel_maintenance_workers=8"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_pdm
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb

volumes:
  timescale_data:
  grafana_data: